# Generated by Django 5.2 on 2025-06-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowstock_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
